version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: NJsonSchema
    versions:
    - 10.3.3
    - 10.3.4
    - 10.3.5
    - 10.3.6
    - 10.3.7
    - 10.3.8
    - 10.3.9
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - 5.0.1
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - 2.16.0
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/System.Management.Automation"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/test/tools/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/src/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
